### ISSUE TITLE
Installation instructions may be optimistic

### ISSUE THREAD

**Issue by ivirshup** [gtca/mudatasets#1]
Is the package on pypi yet? The installation instructions don't seem to work:

```sh
$  pip install mudatasets
ERROR: Could not find a version that satisfies the requirement mudatasets (from versions: none)
ERROR: No matching distribution found for mudatasets
```

Also couldn't find it on pypi: https://pypi.org/search/?q=mudatasets

**Comment by gtca** [comment]
Indeed, we made the repository public a bit earlier than originally planned. This is fixed now: https://pypi.org/project/mudatasets/.
