### ISSUE TITLE
Muon not explicitly a dependency

### ISSUE THREAD

**Issue by ivirshup** [gtca/mudatasets#2]
Loading a dataset depends on muon, but it's not an explicit dependency

```python
brain3k = mudatasets.load("brain3k_multiome")
```

```pytb
/Users/isaac/github/mudatasets/mudatasets/core.py:203: UserWarning: Dataset is in the 10X .h5 format and can't be loaded as backed.
  warn("Dataset is in the 10X .h5 format and can't be loaded as backed.")
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/bd/43q20k0n6z15tdfzxvd22r7c0000gn/T/ipykernel_41886/876042032.py in <module>
----> 1 brain3k = mudatasets.load("brain3k_multiome")

~/github/mudatasets/mudatasets/core.py in load(dataset, data_dir, full, files, version, with_info, backed, chunk_size)
    202             if backed:
    203                 warn("Dataset is in the 10X .h5 format and can't be loaded as backed.")
--> 204             import muon as mu
    205 
    206             print(f"{PREFIX}Loading {os.path.basename(data_path)}...")

ModuleNotFoundError: No module named 'muon'
```

**Comment by gtca** [comment]
Ideally, we would like to have more `.h5mu` files available here — and those one should be able to load just with `mudata` — but loading raw data does indeed require loaders that are in `muon`.

I've added `muon` as an extra dependency at the moment with the idea that we'll make this work:

```py
pip install "mudatasets[muon]"
```

When it's not available, there's a warning now that raw data is downloaded but `muon` is required to work with it.

**Comment by gtca** [comment]
We can consider making it a hard dependency but maybe this solution is a good middle ground for the moment if just `.h5mu` files are of interest.

**Comment by ivirshup** [comment]
Since there's just one dataset which doesn't require muon (right?), maybe it should be a required dependency for now?

**Comment by gtca** [comment]
Makes sense for now I guess. And everything else is in place now to make it optional at some point later.
